server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/videourl
    username: root
    password: root
mybatis:
  type-aliases-package: com.kuaishou.demo.pojo  #别名
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰匹配
